[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[features]
linear = []
root = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"
image = "0.25.0"
